### ISSUE TITLE
TypeError: model.operator.attention_operator.AttentionOperatorConfig() got multiple values for keyword argument 'hidden_size'

### ISSUE THREAD

**Issue by bizbard** [Jyonn/NewsRecommenders#1]
I do follow the lead in the README exactly, but after run the worker.py with the same confs, i got an TypeError as shown in the picture. Could you please tell me how to fix it? @Jyonn Thanks.
`Traceback (most recent call last):
  File "/Users/chuanqijiao/GNRS-master/worker.py", line 395, in <module>
    worker = Worker(config=configuration)
  File "/Users/chuanqijiao/GNRS-master/worker.py", line 54, in __init__
    self.config_manager = ConfigManager(
  File "/Users/chuanqijiao/GNRS-master/loader/config_manager.py", line 219, in __init__
    self.recommender = self.recommender_class(
  File "/Users/chuanqijiao/GNRS-master/model/recommenders/base_neg_recommender.py", line 26, in __init__
    super().__init__(**kwargs)
  File "/Users/chuanqijiao/GNRS-master/model/recommenders/base_recommender.py", line 76, in __init__
    self.user_config = self.user_encoder_class.config_class(
TypeError: model.operator.attention_operator.AttentionOperatorConfig() got multiple values for keyword argument 'hidden_size'
`

**Comment by Jyonn** [comment]
We update the model config parser several days ago, while the config file is not updated.

You can remove redundant lines in `config/model/<model>.yaml` file:


<del>`hidden_size: ${model.config.hidden_size}$`</del>

**Comment by bizbard** [comment]
It seems like it can't store data in the cache for some reasons, even if i set the "filter_cache" flag in config/data/mind.yaml, still run into an error as the figure shows. But i realize the log says "load 0 filter caches on UniDep from data/MIND-small-v2/train", etc. And after preprecessing the data with the processor.py, i notice the "filter" fold in the train/dev/test path is empty. Maybe i did something wrong, could you give me a hint, and explain what the "filter" and "union" flag means in the config/data/mind.yaml?


`[00:00:03] |FCUniDep| load 0 filter caches on UniDep from data/MIND-small-v2/train
loaded 1373519 samples!

[00:00:04] |FCUniDep| load 0 filter caches on UniDep from data/MIND-small-v2/dev
loaded 1367479 samples!

[00:00:04] |FCUniDep| load 0 filter caches on UniDep from data/MIND-small-v2/test
loaded 94057 samples!
loaded 94057 samples!
100%|██████████| 5843444/5843444 [00:26<00:00, 221542.91it/s]

[00:00:31] |FCUniDep| store filter cache on UniDep from data/MIND-small-v2/train
Traceback (most recent call last):
  File "/Users/chuanqijiao/GNRS-master/worker.py", line 395, in <module>
    worker = Worker(config=configuration)
  File "/Users/chuanqijiao/GNRS-master/worker.py", line 54, in __init__
    self.config_manager = ConfigManager(
  File "/Users/chuanqijiao/GNRS-master/loader/config_manager.py", line 171, in __init__
    self.depots = Depots(user_data=self.data.user, modes=self.modes)
  File "/Users/chuanqijiao/GNRS-master/loader/config_manager.py", line 74, in __init__
    depot.filter(filter_func_str, col=col)
  File "/Users/chuanqijiao/GNRS-master/loader/depot/fc_unidep.py", line 125, in filter
    self.store_cache()
  File "/Users/chuanqijiao/GNRS-master/loader/depot/fc_unidep.py", line 87, in store_cache
    self._indexes = [int(i) for i in self._indexes]
AttributeError: 'FCUniDep' object has no attribute '_indexes'`

**Comment by Jyonn** [comment]
Our main framework is under the support of the latest version of UniTok (3.x). It seems that your UniTok version is 2.x for data preprocessing.

**Comment by bizbard** [comment]
I did use the UniTok 2.x for data preprocessing because the "This file requires UniTok~=2.4.3.2, 3.x is not supported." in processor.py and UniTok 3.x does not have .as_list(). So i preprocess the data with UniTok 2.x and run the worker.py with UniTok 3.x. Now the training process runs successfully, hope no further error caused by version conflicts. Thanks.

**Comment by Jyonn** [comment]
Congrats! I will rewrite the preprocess function to support 3.x asap.

**Comment by Jyonn** [comment]
The `filter_cache` is related to `filters` in `user` of `mind.yaml`.

Current filter is written as:
```
  filters:
    history:
      - x
```

which represents that if a user has no history (clicked data), it will not be used in the train/dev/test phase.

It is done after the data preprocessing, and before the model training, which may take times to process (for MIND-small dataset, it may take several minutes). If `filter_cache` is set to `true`, we will store the filtered results to save such processing time.

---

Our data is stored with the following format:

`news`: (nid, title, abs, ...) for each news;
`user`: (uid, history) for each user;
`interaction` (train/dev/test): (index, uid, nid) for each click.

Such store scheme will minimize the storing space.

The core data is the interaction data. To include the user history and negative items (which will be used for BaseNegRecommender), for each (nid, uid) pair, the `union` operation will add `history` and `neg` field based on `uid`.

Do not forget to get neg data by call `p.tokenize_neg()` in `processor.py`.

**Comment by bizbard** [comment]
BTW, why use the negative items? Items user clicks represent user's interest, right? What are the negative items for?

**Comment by Jyonn** [comment]
Matching-based method: to ask the recommender to distinguish the positive item among candidate items (one positive item with K negative items).
