### ISSUE TITLE
How to get original text data in the training process

### ISSUE THREAD

**Issue by bizbard** [Jyonn/NewsRecommenders#3]
I noticed that the data in a batch is represented as Unitok objects, which is the result of tokenization using Unitok (after processor.py). I'm wondering if there is a way to map these tokenized results back to the original text data. For example, if a nid token is 234 that can be mapped to N25648 in the original dataset, then original title data can be found using the N25648 index? Is there a way to do that?

**Comment by Jyonn** [comment]
Yes. You can use UniDep to do that.

For example, your news depot is loaded by:

```python
from UniTok import UniDep

depot = UniDep('/path/to/depot')
nid = depot.id2index['N25648']
news = depot[nid]
```

Here is an example to restore the original data:

```python
text_vocab_name = depot.cols['title'].voc.name
text_vocab = depot.vocabs[text_vocab_name]  
# text_vocab = depot.cols['title'].voc.vocab  # UniTok version >= 3.1.9

for attr in ['title', 'abs']:
  print(attr, '\t:', end=' ')
  print(' '.join([text_vocab[value] for value in news[attr]]))

cat_vocab_name = depot.cols['cat'].voc.name
cat_vocab = depot.vocabs[cat_vocab_name]
print('cat', '\t: ', cat_vocab[news['cat']])

id_vocab_name = depot.cols['nid'].voc.name
id_vocab = depot.vocabs[id_vocab_name]
print('nid', '\t: ', id_vocab[news['nid']])
``` 

**Note that, the tokenized data can not be fully recovered due to truncation.**

The usage of `Vocab` class is as follows:

```python
id_vocab: Vocab

id_vocab[234]  # N25648
id_vocab.i2o[234]  # N25648

id_vocab['N25648']  # 234
id_vocab.o2i['N25648']  # 234

# depot.id2index is equal to id_vocab.o2i
```

**Comment by bizbard** [comment]
Thanks! That truly helps!
